-- CreateTable
CREATE TABLE "public"."activity" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "resourceState" INTEGER NOT NULL,
    "athleteId" INTEGER,
    "athleteResourceState" INTEGER,
    "name" TEXT NOT NULL,
    "distance" DOUBLE PRECISION NOT NULL,
    "movingTime" INTEGER NOT NULL,
    "elapsedTime" INTEGER NOT NULL,
    "totalElevationGain" DOUBLE PRECISION NOT NULL,
    "type" TEXT NOT NULL,
    "sportType" TEXT NOT NULL,
    "workoutType" INTEGER,
    "startDate" TIMESTAMP(3) NOT NULL,
    "startDateLocal" TIMESTAMP(3) NOT NULL,
    "timezone" TEXT,
    "utcOffset" INTEGER,
    "locationCity" TEXT,
    "locationState" TEXT,
    "locationCountry" TEXT,
    "achievementCount" INTEGER NOT NULL,
    "kudosCount" INTEGER NOT NULL,
    "commentCount" INTEGER NOT NULL,
    "athleteCount" INTEGER NOT NULL,
    "photoCount" INTEGER NOT NULL,
    "mapId" TEXT,
    "summaryPolyline" TEXT,
    "mapResourceState" INTEGER,
    "trainer" BOOLEAN NOT NULL,
    "commute" BOOLEAN NOT NULL,
    "manual" BOOLEAN NOT NULL,
    "private" BOOLEAN NOT NULL,
    "visibility" TEXT,
    "flagged" BOOLEAN NOT NULL,
    "gearId" TEXT,
    "startLat" DOUBLE PRECISION,
    "startLng" DOUBLE PRECISION,
    "endLat" DOUBLE PRECISION,
    "endLng" DOUBLE PRECISION,
    "averageSpeed" DOUBLE PRECISION,
    "maxSpeed" DOUBLE PRECISION,
    "hasHeartrate" BOOLEAN NOT NULL,
    "averageHeartrate" DOUBLE PRECISION,
    "maxHeartrate" DOUBLE PRECISION,
    "heartrateOptOut" BOOLEAN NOT NULL,
    "displayHideHeartrateOption" BOOLEAN NOT NULL,
    "elevHigh" DOUBLE PRECISION,
    "elevLow" DOUBLE PRECISION,
    "uploadId" BIGINT,
    "uploadIdStr" TEXT,
    "externalId" TEXT,
    "fromAcceptedTag" BOOLEAN NOT NULL,
    "prCount" INTEGER NOT NULL,
    "totalPhotoCount" INTEGER NOT NULL,
    "hasKudoed" BOOLEAN NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "activity_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "activity_id_userId_key" ON "public"."activity"("id", "userId");

-- AddForeignKey
ALTER TABLE "public"."activity" ADD CONSTRAINT "activity_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
